stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - make
    - mvn compile
  tags:
    - shell

test:
  stage: test
  script:
    - make
    - mvn compile
    - mvn test
  tags:
    - shell