#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

if ARGV.length != 1
    puts "please give the path to the source .wacc file!"
    exit
end

output = system('java -cp target/wacc_49-1.0-SNAPSHOT.jar:lib/* doc.wacc.Wacc ' + ARGV[0])

puts "exit(%d)" %[$?.exitstatus]

exit $?.exitstatus
